"""Core data models for Stitch.

All models are plain dataclasses serializable to/from JSON and Markdown.
No external dependencies — stdlib only.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Optional


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _new_id() -> str:
    return uuid.uuid4().hex[:12]


@dataclass
class Decision:
    id: str = field(default_factory=_new_id)
    task_id: str = ""
    timestamp: str = field(default_factory=_now_iso)
    problem: str = ""
    chosen: str = ""
    alternatives: list[str] = field(default_factory=list)
    tradeoffs: str = ""
    reasoning: str = ""

    def to_markdown(self) -> str:
        alts = "\n".join(f"  - {a}" for a in self.alternatives) if self.alternatives else "  - (none)"
        return (
            f"### {self.problem}\n"
            f"- **Date**: {self.timestamp}\n"
            f"- **Chosen**: {self.chosen}\n"
            f"- **Alternatives**:\n{alts}\n"
            f"- **Tradeoffs**: {self.tradeoffs}\n"
            f"- **Reasoning**: {self.reasoning}\n"
        )


@dataclass
class Snapshot:
    id: str = field(default_factory=_new_id)
    task_id: str = ""
    timestamp: str = field(default_factory=_now_iso)
    message: str = ""
    source: str = "manual"  # manual | git-hook | daemon | agent
    git_branch: str = ""
    git_diff_stat: str = ""
    git_status: str = ""
    git_log_short: str = ""
    files_changed: list[str] = field(default_factory=list)
    extra: dict = field(default_factory=dict)

    def to_markdown(self) -> str:
        parts = [f"### [{self.timestamp}] {self.message} ({self.source})"]
        if self.git_branch:
            parts.append(f"**Branch**: `{self.git_branch}`")
        if self.git_status:
            parts.append(f"**Status**:\n```\n{self.git_status[:500]}\n```")
        if self.git_diff_stat:
            parts.append(f"**Diff stat**:\n```\n{self.git_diff_stat[:500]}\n```")
        if self.git_log_short:
            parts.append(f"**Recent commits**:\n```\n{self.git_log_short[:300]}\n```")
        return "\n".join(parts)


@dataclass
class Task:
    id: str = field(default_factory=_new_id)
    title: str = ""
    project_path: str = ""
    status: str = "active"  # active | paused | completed | abandoned
    tags: list[str] = field(default_factory=list)
    objective: str = ""
    current_state: str = ""
    next_steps: str = ""
    blockers: str = ""
    created_at: str = field(default_factory=_now_iso)
    updated_at: str = field(default_factory=_now_iso)

    def touch(self):
        self.updated_at = _now_iso()


@dataclass
class HandoffBundle:
    """Token-budget-aware summary for handing off to a new agent."""

    task: Task
    recent_snapshots: list[Snapshot] = field(default_factory=list)
    key_decisions: list[Decision] = field(default_factory=list)
    token_budget: int = 3000

    def to_markdown(self) -> str:
        lines = [
            "# Stitch Handoff Bundle",
            "",
            f"**Task**: {self.task.title} (`{self.task.id}`)",
            f"**Project**: `{self.task.project_path}`",
            f"**Status**: {self.task.status}",
            f"**Created**: {self.task.created_at}",
            "",
            "## Objective",
            self.task.objective or "(not set)",
            "",
            "## Current State",
            self.task.current_state or "(not set)",
            "",
            "## Next Steps",
            self.task.next_steps or "(not set)",
            "",
        ]

        if self.task.blockers:
            lines += ["## Blockers", self.task.blockers, ""]

        if self.key_decisions:
            lines += ["## Key Decisions"]
            for d in self.key_decisions[-5:]:
                lines.append(d.to_markdown())
                lines.append("")

        if self.recent_snapshots:
            lines += ["## Recent Activity"]
            for s in self.recent_snapshots[-5:]:
                lines.append(s.to_markdown())
                lines.append("")

        lines += [
            "---",
            "*Generated by Stitch v0.2.0. "
            "Read `.stitch/tasks/{id}/` for full context.*",
        ]

        bundle = "\n".join(lines)
        # Rough token estimate: ~4 chars per token
        est_tokens = len(bundle) // 4
        if est_tokens > self.token_budget:
            bundle = self._trim(bundle)
        return bundle

    def _trim(self, text: str) -> str:
        """Trim to fit within token budget (rough heuristic: 4 chars/token)."""
        max_chars = self.token_budget * 4
        if len(text) <= max_chars:
            return text
        return text[:max_chars] + "\n\n... (trimmed to fit token budget) ..."

    def to_prompt(self) -> str:
        """Generate a copy-pasteable prompt for a new agent session."""
        return (
            "I am resuming work on a task. Below is the full context from the "
            "previous session(s). Read it carefully, then summarize your understanding "
            "and propose next steps.\n\n"
            + self.to_markdown()
        )


def to_json(obj) -> str:
    return json.dumps(asdict(obj), indent=2, default=str)


def from_json(cls, data: str | dict):
    if isinstance(data, str):
        data = json.loads(data)
    return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})
